plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.86'
}


version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
//            programArgument('--username=Tazer')
            jvmArgument('-Ddevauth.enabled=true')
            jvmArgument('-Ddevauth.account=main')
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()

            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "$mod_id" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    mavenCentral()
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven { url "https://maven.blamejared.com/" }
    maven { url "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1" }
    maven { url 'https://maven.terraformersmc.com/' }
    flatDir { dirs 'libs' }
}

dependencies {
//    implementation("foundry.veil:veil-neoforge-$minecraft_version:$veil_version") {
//        exclude group: "maven.modrinth"
//    }

    implementation "com.terraformersmc:biolith-neoforge:$bt_version"
    implementation "maven.modrinth:mixed-litter:$ml_version"
    jarJar(implementation("com.moulberry:mixinconstraints:1.0.7") {
                exclude group: "org.slf4j",
                        module: "slf4j-api"
    })

    implementation "maven.modrinth:farmers-delight:1.21.1-1.2.7"
    compileOnly "maven.modrinth:brewin-and-chewin:4.2.0+1.21.1-neoforge"
    compileOnly "maven.modrinth:the-block-box:0.1.1"
    compileOnly "maven.modrinth:create:1.21.1-6.0.4"
    compileOnly "maven.modrinth:blueprint:8.0.3"
    compileOnly "maven.modrinth:boatload:6.0.0"

    compileOnly "maven.modrinth:jade:15.10.0+neoforge"
    compileOnly "maven.modrinth:serene-seasons:SPj5bJoM"
    compileOnly "maven.modrinth:glitchcore:8wmCpbQ2"
    compileOnly "maven.modrinth:supplementaries:neoforge_1.21-3.0.43-beta"
    compileOnly "maven.modrinth:moonlight:neoforge_1.21-2.17.37"

    compileOnly "mezz.jei:jei-$minecraft_version-common-api:$jei_version"
    compileOnly "mezz.jei:jei-$minecraft_version-neoforge-api:$jei_version"
    localRuntime "mezz.jei:jei-$minecraft_version-neoforge:$jei_version"

    localRuntime "maven.modrinth:xaeros-world-map:1.38.9_NeoForge_1.21"
    localRuntime "maven.modrinth:appleskin:3.0.5+mc1.21"
    localRuntime "maven.modrinth:worldedit:7.3.6"
    localRuntime "maven.modrinth:sodium:mc1.21.1-0.6.9-neoforge"
    localRuntime "me.djtheredstoner:DevAuth-neoforge:1.2.1"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            bt_version_range       : bt_version_range,
            ml_version_range       : ml_version_range
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}