org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

## Environment Properties
# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
# Neoforge
neo_version=21.1.138
neo_version_range=[21.1.0,)
loader_version_range=[4,)
# JEI
jei_version=19.21.0.247

## No Man's Land Properties
mod_id=nomansland
mod_name=No Man's Land
mod_license=All Rights Reserved
mod_version=1.2.3
mod_group_id=com.farcr.nomansland
mod_authors=Farcr, Tazer, and many Contributors
mod_description=A vanilla-friendly overhaul that improves your Overworld, enhancing biomes and adding new ones alike - transforming the world with _great care to detail_ in every one of its aspects. From the tallest mountain peaks to the deepest of oceanic trenches, No Man's Land seeks to bring every single environment to the same level of quality and care. This mod is, at its core, supposed to enhance your Gameplay, and as such has all of its features designed to be greatly interactive and allowing of creative freedom. Everything in creation is blessed by beauty, and You are an inseparable part of it. So explore, and love as this world loves you.

## Dependency Properties
# Biolith
bt_version=3.0.1
bt_version_range=[3.0.1,)
# Mixed Litter
ml_version=0.1.1
ml_version_range=[0.1.0,)